services:
  - type: web
    name: macktech
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: node server.js
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    autoDeploy: true
